// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3cC7WjaNuYwYEhKFb9Lc75sbuKiKc5jk',
    appId: '1:606195344134:web:cbc9acaf13f23287763487',
    messagingSenderId: '606195344134',
    projectId: 'horizon-2e9f0',
    authDomain: 'horizon-2e9f0.firebaseapp.com',
    storageBucket: 'horizon-2e9f0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPVRbkK55_oQBQ-juiHFbsYT3xLT5Qg7s',
    appId: '1:606195344134:android:5cdc5e47b2b5ba45763487',
    messagingSenderId: '606195344134',
    projectId: 'horizon-2e9f0',
    storageBucket: 'horizon-2e9f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbqutwMHuKSbfAdaB0UlSlJnaV0rmE41c',
    appId: '1:606195344134:ios:9df22c8ec8e013be763487',
    messagingSenderId: '606195344134',
    projectId: 'horizon-2e9f0',
    storageBucket: 'horizon-2e9f0.appspot.com',
    iosBundleId: 'com.example.horizon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbqutwMHuKSbfAdaB0UlSlJnaV0rmE41c',
    appId: '1:606195344134:ios:5bb35b6eb8b99ebb763487',
    messagingSenderId: '606195344134',
    projectId: 'horizon-2e9f0',
    storageBucket: 'horizon-2e9f0.appspot.com',
    iosBundleId: 'com.example.horizon.RunnerTests',
  );
}
